"""Renders docker-compose.yml (and the OTel Collector config it mounts)
for `harness dev` — a developer never hand-writes either.

The generated compose file lives under `<workspace_root>/.harness/`,
not the workspace root itself, so every path it references is written
absolute rather than relative — relative paths in a compose file
resolve against *that file's* directory, which would otherwise silently
point bind mounts and build contexts at the wrong place.
"""

from __future__ import annotations

from pathlib import Path

_OTEL_COLLECTOR_IMAGE = "otel/opentelemetry-collector-contrib:0.116.1"
_JAEGER_IMAGE = "jaegertracing/all-in-one:1.76.0"


def render_otel_collector_config() -> str:
    return """\
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  debug:
    verbosity: basic
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger, debug]
"""


def render_compose(
    *,
    agent_name: str,
    workspace_root: Path,
    agent_dir: Path,
    agent_dockerfile: Path,
    otel_collector_config: Path,
    agent_port: int = 8080,
    dashboard_port: int = 3400,
    api_token: str | None = None,
    llm_provider: str | None = None,
    ollama_base_url: str | None = None,
) -> str:
    extra_env: dict[str, str] = {}
    if api_token:
        extra_env["HARNESS_API_TOKEN"] = api_token
    if llm_provider:
        extra_env["HARNESS_LLM_PROVIDER"] = llm_provider
    if ollama_base_url:
        extra_env["HARNESS_OLLAMA_BASE_URL"] = ollama_base_url
    extra_env_lines = "".join(f"\n      {key}: {value}" for key, value in extra_env.items())
    dashboard_dockerfile = workspace_root / "src" / "harness_cli" / "dashboard" / "Dockerfile"
    return f"""\
# Generated by `harness dev` — do not hand-edit; re-run `harness dev`
# to regenerate after changing your agent's pyproject.toml.
name: harness-{agent_name}

services:
  agent:
    build:
      context: {workspace_root}
      dockerfile: {agent_dockerfile}
      target: dev
    ports:
      - "{agent_port}:{agent_port}"
    volumes:
      - {agent_dir}:/app/agent_src
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318{extra_env_lines}
    depends_on:
      - otel-collector

  otel-collector:
    image: {_OTEL_COLLECTOR_IMAGE}
    volumes:
      - {otel_collector_config}:/etc/otelcol-contrib/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger

  jaeger:
    image: {_JAEGER_IMAGE}
    ports:
      - "16686:16686"

  dashboard:
    build:
      context: {workspace_root}
      dockerfile: {dashboard_dockerfile}
    ports:
      - "{dashboard_port}:3000"
    environment:
      HARNESS_AGENT_CARD_URL: http://localhost:{agent_port}/.well-known/agent-card.json
      HARNESS_JAEGER_URL: http://localhost:16686
"""
