"""Renders the Dockerfile a developer never has to hand-write.

Build context is always the Harness workspace root (not the agent's own
directory), since `a2a-harness` isn't published yet — the image installs
it from source alongside the agent's own module. Three stages/targets:
`builder` (shared deps layer), `dev` (hot reload, used by `harness dev`),
`runtime` (the actual deploy unit: non-root, healthcheck, exec-form CMD
for clean SIGTERM handling).
"""

from __future__ import annotations

_UV_IMAGE = "ghcr.io/astral-sh/uv:0.12.17"
_PYTHON_IMAGE = "python:3.12-slim"


def render_dockerfile(*, entrypoint: str, agent_dir: str, port: int = 8080) -> str:
    """`agent_dir` is the agent's directory relative to the build context
    (the Harness workspace root), e.g. `examples/research-agent`.
    `entrypoint` is `module:ClassName` for the `@agent`-decorated class."""
    healthcheck_url = f"http://localhost:{port}/healthz"
    return f"""\
# syntax=docker/dockerfile:1
# Generated by `harness build` — do not hand-edit; changes belong in
# your agent's pyproject.toml / harness.toml, not here.

FROM {_PYTHON_IMAGE} AS builder
COPY --from={_UV_IMAGE} /uv /usr/local/bin/uv
ENV UV_COMPILE_BYTECODE=1 \\
    UV_LINK_MODE=copy \\
    UV_NO_MANAGED_PYTHON=1
WORKDIR /app
COPY pyproject.toml uv.lock README.md ./
RUN --mount=type=cache,target=/root/.cache/uv \\
    uv sync --frozen --no-install-project --no-dev
COPY src ./src
RUN --mount=type=cache,target=/root/.cache/uv \\
    uv sync --frozen --no-dev
COPY {agent_dir} ./agent_src

FROM builder AS dev
ENV PATH="/app/.venv/bin:$PATH" \\
    PYTHONUNBUFFERED=1 \\
    PYTHONPATH=/app/agent_src \\
    HARNESS_ENTRYPOINT={entrypoint} \\
    HARNESS_PORT={port}
EXPOSE {port}
CMD ["uvicorn", "harness._internal.runtime:build_asgi_app", "--factory", \\
     "--host", "0.0.0.0", "--port", "{port}", "--reload", \\
     "--reload-dir", "/app/agent_src"]

FROM {_PYTHON_IMAGE} AS runtime
RUN groupadd -r harness && useradd -r -g harness -u 10001 harness
WORKDIR /app
COPY --from=builder /app/.venv ./.venv
COPY --from=builder /app/src ./src
COPY --from=builder /app/agent_src ./agent_src
ENV PATH="/app/.venv/bin:$PATH" \\
    PYTHONUNBUFFERED=1 \\
    PYTHONPATH=/app/agent_src \\
    HARNESS_ENTRYPOINT={entrypoint} \\
    HARNESS_PORT={port}
USER harness
EXPOSE {port}
HEALTHCHECK --interval=10s --timeout=3s --start-period=5s --retries=3 \\
    CMD python -c "import urllib.request as u; u.urlopen({healthcheck_url!r}, timeout=2)" \\
    || exit 1
CMD ["uvicorn", "harness._internal.runtime:build_asgi_app", "--factory", \\
     "--host", "0.0.0.0", "--port", "{port}"]
"""
