"""Renders the Dockerfile a developer never has to hand-write.

Three renderers, matching `harness_cli.project`'s two agent layouts
plus the dashboard's own build:

- `render_dockerfile` (monorepo agent) — build context is the Harness
  workspace root, since `a2a-harness` isn't published anywhere; the
  image installs it from local source (editable) alongside the agent's
  own module.
- `render_standalone_dockerfile` (standalone agent) — build context is
  the agent's own directory; `a2a-harness` installs like any other
  dependency, from wherever the agent's own `pyproject.toml` points it
  (a git dependency pinned to a released tag, in the common case) — no
  local Harness source needs to be present at all.
- `render_standalone_dashboard_dockerfile` — the dashboard, when the
  agent is standalone, has the same "no local Harness source" problem
  as the agent itself; installs `a2a-harness` from git too, matching
  whatever ref the agent pins.

The two agent renderers produce the same three stages/targets:
`builder` (shared deps layer), `dev` (hot reload, used by `harness
dev`), `runtime` (the actual deploy unit: non-root, healthcheck,
exec-form CMD for clean SIGTERM handling).
"""

from __future__ import annotations

_UV_IMAGE = "ghcr.io/astral-sh/uv:0.12.17"
_PYTHON_IMAGE = "python:3.12-slim"


def render_dockerfile(*, entrypoint: str, agent_dir: str, port: int = 8080) -> str:
    """`agent_dir` is the agent's directory relative to the build context
    (the Harness workspace root), e.g. `examples/research-agent`.
    `entrypoint` is `module:ClassName` for the `@agent`-decorated class."""
    healthcheck_url = f"http://localhost:{port}/healthz"
    return f"""\
# syntax=docker/dockerfile:1
# Generated by `harness build` — do not hand-edit; changes belong in
# your agent's pyproject.toml / harness.toml, not here.

FROM {_PYTHON_IMAGE} AS builder
COPY --from={_UV_IMAGE} /uv /usr/local/bin/uv
ENV UV_COMPILE_BYTECODE=1 \\
    UV_LINK_MODE=copy \\
    UV_NO_MANAGED_PYTHON=1
WORKDIR /app
COPY pyproject.toml uv.lock README.md ./
RUN --mount=type=cache,target=/root/.cache/uv \\
    uv sync --frozen --no-install-project --no-dev
COPY src ./src
RUN --mount=type=cache,target=/root/.cache/uv \\
    uv sync --frozen --no-dev
COPY {agent_dir} ./agent_src

FROM builder AS dev
ENV PATH="/app/.venv/bin:$PATH" \\
    PYTHONUNBUFFERED=1 \\
    PYTHONPATH=/app/agent_src \\
    HARNESS_ENTRYPOINT={entrypoint} \\
    HARNESS_PORT={port}
EXPOSE {port}
CMD ["uvicorn", "harness._internal.runtime:build_asgi_app", "--factory", \\
     "--host", "0.0.0.0", "--port", "{port}", "--reload", \\
     "--reload-dir", "/app/agent_src"]

FROM {_PYTHON_IMAGE} AS runtime
RUN groupadd -r harness && useradd -r -g harness -u 10001 harness
WORKDIR /app
COPY --from=builder /app/.venv ./.venv
COPY --from=builder /app/src ./src
COPY --from=builder /app/agent_src ./agent_src
ENV PATH="/app/.venv/bin:$PATH" \\
    PYTHONUNBUFFERED=1 \\
    PYTHONPATH=/app/agent_src \\
    HARNESS_ENTRYPOINT={entrypoint} \\
    HARNESS_PORT={port}
USER harness
EXPOSE {port}
HEALTHCHECK --interval=10s --timeout=3s --start-period=5s --retries=3 \\
    CMD python -c "import urllib.request as u; u.urlopen({healthcheck_url!r}, timeout=2)" \\
    || exit 1
CMD ["uvicorn", "harness._internal.runtime:build_asgi_app", "--factory", \\
     "--host", "0.0.0.0", "--port", "{port}"]
"""


def render_standalone_dockerfile(*, entrypoint: str, port: int = 8080) -> str:
    """For an agent that's its own repo, depending on `a2a-harness` as a
    normal dependency in its own pyproject.toml/uv.lock. Build context is
    the agent's own directory — passed as `.` here since it's copied
    wholesale, not from a named subdirectory the way monorepo mode is."""
    healthcheck_url = f"http://localhost:{port}/healthz"
    return f"""\
# syntax=docker/dockerfile:1
# Generated by `harness build` — do not hand-edit; changes belong in
# your agent's pyproject.toml, not here.

FROM {_PYTHON_IMAGE} AS builder
COPY --from={_UV_IMAGE} /uv /usr/local/bin/uv
ENV UV_COMPILE_BYTECODE=1 \\
    UV_LINK_MODE=copy \\
    UV_NO_MANAGED_PYTHON=1
WORKDIR /app
# git is needed here (not in monorepo mode's Dockerfile) because
# a2a-harness resolves from a git dependency in a standalone agent's
# own pyproject.toml, and python:3.12-slim doesn't ship git.
RUN apt-get update && apt-get install -y --no-install-recommends git \\
    && rm -rf /var/lib/apt/lists/*
COPY pyproject.toml uv.lock ./
RUN --mount=type=cache,target=/root/.cache/uv \\
    uv sync --frozen --no-dev
COPY . ./agent_src

FROM builder AS dev
ENV PATH="/app/.venv/bin:$PATH" \\
    PYTHONUNBUFFERED=1 \\
    PYTHONPATH=/app/agent_src \\
    HARNESS_ENTRYPOINT={entrypoint} \\
    HARNESS_PORT={port}
EXPOSE {port}
CMD ["uvicorn", "harness._internal.runtime:build_asgi_app", "--factory", \\
     "--host", "0.0.0.0", "--port", "{port}", "--reload", \\
     "--reload-dir", "/app/agent_src"]

FROM {_PYTHON_IMAGE} AS runtime
RUN groupadd -r harness && useradd -r -g harness -u 10001 harness
WORKDIR /app
COPY --from=builder /app/.venv ./.venv
COPY --from=builder /app/agent_src ./agent_src
ENV PATH="/app/.venv/bin:$PATH" \\
    PYTHONUNBUFFERED=1 \\
    PYTHONPATH=/app/agent_src \\
    HARNESS_ENTRYPOINT={entrypoint} \\
    HARNESS_PORT={port}
USER harness
EXPOSE {port}
HEALTHCHECK --interval=10s --timeout=3s --start-period=5s --retries=3 \\
    CMD python -c "import urllib.request as u; u.urlopen({healthcheck_url!r}, timeout=2)" \\
    || exit 1
CMD ["uvicorn", "harness._internal.runtime:build_asgi_app", "--factory", \\
     "--host", "0.0.0.0", "--port", "{port}"]
"""


def render_standalone_dashboard_dockerfile(*, git_url: str, git_ref: str | None) -> str:
    """The dashboard for a standalone agent can't copy local `harness_cli`
    source the way monorepo mode's dashboard/Dockerfile does — there's no
    local Harness checkout in a standalone agent's repo at all. Installs
    `a2a-harness` from the same git source (and ref) the agent's own
    pyproject.toml pins, so the dashboard matches the agent's harness_cli
    version rather than assuming a fixed repo. Build context is
    irrelevant here — nothing local gets copied in."""
    source = f"a2a-harness @ git+{git_url}"
    if git_ref:
        source += f"@{git_ref}"
    return f"""\
# syntax=docker/dockerfile:1
# Generated by `harness dev` — do not hand-edit.

FROM {_PYTHON_IMAGE}
COPY --from={_UV_IMAGE} /uv /usr/local/bin/uv
ENV UV_COMPILE_BYTECODE=1 \\
    UV_LINK_MODE=copy \\
    UV_NO_MANAGED_PYTHON=1
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends git \\
    && rm -rf /var/lib/apt/lists/*
RUN uv venv && uv pip install {source!r}
ENV PATH="/app/.venv/bin:$PATH" \\
    PYTHONUNBUFFERED=1
EXPOSE 3000
CMD ["uvicorn", "harness_cli.dashboard.app:app", "--host", "0.0.0.0", "--port", "3000"]
"""
